name: discord_price_watcher
description: A discord price watcher bot
version: 0.2.0

dependencies:
  html:
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: development
  http: ^0.12.1
  path: ^1.7.0

environment:
  sdk: '>=2.1.0 <3.0.0'