name: rightstuf_price_watcher
description: A price watcher bot
version: 0.0.1

dependencies:
  html:
  nyxx:
    git:
      url: git://github.com/l7ssha/nyxx.git
      ref: development
  http: ^0.12.1
  dio: ^3.0.9

environment:
  sdk: '>=2.1.0 <3.0.0'